/** @type {import('tailwindcss').Config} */
const colors = require("tailwindcss/colors");
const colorClasses = {
    color1: "#17223B",
    color2: "#1f4287",
    color3: "#278ea5",
    color4: "#74B9FF",
    black: "#000000",
    dark: "#161616",
    white: "#FFFFFF",
    red: "#FF6B6B",
    green: "#88D498",
    grayBlue: "#c7d2da",
    gray: colors.gray,
    ligthGreen: "#54ffaf",
    redLight: "#ff6464",
    background: "#edf0f0",
    transparent: "transparent",
    zelle: "#6a1ccd",
    binance: "#F3BA2F",
    yellow: "#FFD23F",
    purple: "#b8a9fa",
    orange: "#FFA552",
    blue: "#74b9ff",
};
module.exports = {
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.svelte",
    ],
    safelist: [
        ...Object.keys(colorClasses).map((color) => `border-${color}`),
        ...Object.keys(colorClasses).map((color) => `hover:bg-${color}`),
        ...Object.keys(colorClasses).map((color) => `bg-${color}`),
    ],
    theme: {
        colors: {
            color1: "#17223B",
            color2: "#1f4287",
            color3: "#278ea5",
            color4: "#74B9FF",
            black: "#000000",
            dark: "#161616",
            white: "#FFFFFF",
            red: "#FF6B6B",
            green: "#88D498",
            grayBlue: "#c7d2da",
            gray: colors.gray,
            ligthGreen: "#54ffaf",
            redLight: "#ff6464",
            background: "#edf0f0",
            transparent: "transparent",
            zelle: "#6a1ccd",
            binance: "#F3BA2F",
            yellow: "#FFD23F",
            purple: "#b8a9fa",
            orange: "#FFA552",
            blue: "#74b9ff",
        },
        extend: {},
    },
    plugins: [],
};
